#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Command\ReportCommand;

$application = new Application();

$application->add(new ReportCommand());

$application->run();

